### ISSUE TITLE
master branch line142:  const accountId = msg.args?.[1];

### ISSUE THREAD

**Issue by kongcheng1400** [ZigZagExchange/market-maker#62]
seems a code problem here. how this "args?" come?
Cheers
Harry.

**Comment by TrooperCrypto** [comment]
Hey sorry for the late resopnse. Is oyur questions why I added the '?' after the value ? Its called 'optional chaining' and is used to savely access nested values - in some cases args might not be defined and the result is null rahter than throwing an error. YOu can read more here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Let me know if you have more questions :)

**Comment by kongcheng1400** [comment]
my bad... I am still learning. it's not issue, indeed it's optional parameter.
Closing this.
Cheers
Harry.
