### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by in-chong** [ZigZagExchange/market-maker#77]
why my fillable is always false ? even
[here](https://user-images.githubusercontent.com/39892972/168309967-4057f0c3-8bbc-4a4a-aebb-9ce476581e8f.png)

Cheers
Harry.

**Comment by TrooperCrypto** [comment]
Hey, not sure I understand you problem. Its a sell order and the bot expects less then $2136 and only got $2457. So it correctly rejects the order.

**Comment by in-chong** [comment]
Well, I mean I don't have a qualified order so far,so  I can not sendFillRequest
[here](https://user-images.githubusercontent.com/39892972/168427050-6696cd41-639d-4859-a973-eecb1664684d.png)
so when or how to get one qualified order
thanks

**Comment by in-chong** [comment]
Well,may the bot is always push orders that do not meet the conditions ?
